### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by beppe9000** [thomaslevesque/NHotkey#10]
I tried to use this library in VB.Net but it does not register hotkeys. Here is the relevant code.

```
Dim hk = Keys.ControlKey Or Keys.H

Dim hh = Sub(s, e)
             MsgBox("HIT")
             e.Handled = True
        End Sub

NHotkey.WindowsForms.HotkeyManager.Current.AddOrReplace("WinToggle", hk, hh)
```

**Comment by thomaslevesque** [comment]
Sorry for the delay, I was on holidays...
You should use `Control` instead of `ControlKey`

**Comment by beppe9000** [comment]
I didn't really expect a reply :)
But thanks, it finally worked!
<hr>
Could you tell me the difference between `Control` and `ControlKey` ?
For example what should I (theoretically) press to trigger the message box in my example code? I see the description in the documentation is the same :\

**Comment by thomaslevesque** [comment]
> Could you tell me the difference between Control and ControlKey ?

Good question... according to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=netframework-4.7.1), `Control` is the CTRL _modifier_ key, whereas `ControlKey` is the CTRL key itself (i.e. not as a modifier).

> For example what should I (theoretically) press to trigger the message box in my example code? I see the description in the documentation is the same :\

<kbd>Y</kbd>, which is the result of `Keys.ControlKey Or Keys.H` (bitwise OR between the values of `ControlKey` and `H`). But it wouldn't work, because it doesn't include a modifier key, and you can't register unmodified keys as hotkeys.

Since ControlKey isn't a modifier key, it's not designed to be combined with another key.
