### ISSUE TITLE
need help defining multiple hotkeys

### ISSUE THREAD

**Issue by jfayre** [thomaslevesque/NHotkey#25]
Hello,
I'm fairly new to c#. My application needs to define multiple hotkeys, which are being read from an ini file.
The ini file format for a key looks like this:
director_key = 2,49
This would be ctrl+f.
When I try to pass the key 49, and the modifier 2 (ctrl), I get the following error:
Error	CS1503	Argument 2: cannot convert from 'string' to 'System.Windows.Input.KeyGesture'	
I'm sure there's something relatively simple I'm missing here, I just can't quite figure this out.
I'm defining all the keys in a foreach loop that steps through my ini file.

**Comment by thomaslevesque** [comment]
Hi @jfayre,

You need to convert the values from the INI file to `Key` and `ModifierKeys`. Since they're stored as strings containing the integer value, you first need to convert them to integers, then to the enum value.

```csharp
	// actually get the values from the INI file
	string modifierString = "2";
	string keyString = "49";
	
	// convert to integer, then to enum
	ModifierKeys modifiers = (ModifierKeys) Enum.ToObject(typeof(ModifierKeys), int.Parse(modifierString));
	Key key = (Key) Enum.ToObject(typeof(Key), int.Parse(keyString));
```

To be honest, I think the format you're using to store the hotkeys in configuration is a bit strange. Why not store them as a string like "Ctrl+F" for instance? It could then be easily parsed to a `KeyGesture` like this:

```csharp
var converter = new KeyGestureConverter();
var gesture = (KeyGesture)converter.ConvertFrom("Ctrl+F");
HotkeyManager.Current.AddOrReplace("director_key", gesture, handler);
```

**Comment by jfayre** [comment]
Perfect, thanks! I did read about the string conversion, just wasn’t sure how to make that work. I’m learning as I go here.

I’m not stuck to any particular ini file format, so I’ll probably change to the string format for keys.

**Comment by thomaslevesque** [comment]
Always glad to help!
I'll close this issue now

**Comment by jfayre** [comment]
Hello!
I'm just getting back to this after working on a bunch of other stuff.
I discovered I actually can't use the string converter. The reason is that my software uses a layered command approach. Since I'm writing an accessibility add-on for Microsoft Flight Simulator, I need keys that don't conflict with the million keys that Microsoft already defines.
So, what I do is bind the right square bracket key, once you press that key, I register a bunch of other keys. Some of them have modifiers, some are just the key, such as pressing a for speaking of the altitude. After you press the second key, all those keys get unregistered until you press the right bracket key again.
This is actually wworking correctly. The problem is that Microsoft doesn't let you use the key gesture converter with a key that doesn't have a modifier. It just throws an exception. For some reason not using the key converter as mentioned above does work, although I'm not sure how, since Microsoft doesn't like people doing this. 
I'm guessing your bypassing the standard key gesture system some how to allow individual keys to be registered as global?
I just want to make sure I'm not going to code all this and then have everything stop working because MS depricates something.
Any thoughts?

**Comment by thomaslevesque** [comment]
> I'm guessing your bypassing the standard key gesture system some how to allow individual keys to be registered as global?

Nope. I use the `KeyGesture` in NHotkey because it's convenient, but the underlying Win32 API ([`RegisterHotkey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey)) just uses integers. I convert from `KeyGesture` to the arguments `RegisterHotkey` expects.

I don't do anything to allow individual keys to be registered as global. In fact, I'm pretty sure `RegisterHotkey` doesn't allow this.
