### ISSUE TITLE
Parameters to event handler

### ISSUE THREAD

**Issue by brutalzinn** [thomaslevesque/NHotkey#26]
How can i pass parameters to event handler method? I am stopped about one hour on it

**Comment by Lakritzator** [comment]
I don't think one can really answer your question without having more information.
But in general one doesn't pass parameters to an event handler method, as this is specific to the event, if you want to get some information you will need to retrieve it from somewhere in your handler.

**Comment by thomaslevesque** [comment]
Hi @brutalzinn,

@Lakritzator is correct. You can't pass your own parameters to the event handler, because you're not the one who calls it. And anyway, you can't change the event handler signature. This is true for all events, and is not specific to NHotkey.

@brutalzinn it might be possible to help you if you provide more information about what you're trying to do; however, since your question isn't specific to NHotkey, I suggest you ask it on StackOverflow instead.

**Comment by brutalzinn** [comment]
Hello. Sorry for my wrong responde type. I resolved this issue  creating a public classe, with my params and my event method. I create a instance of this class when a creat a global key

**Comment by thomaslevesque** [comment]
Hi @brutalzinn,

Glad you could find a solution. I'll close this issue now.

**Comment by rhyland** [comment]
brutalzinn :  could you please post some code samples of what you did to resolve this issue, thanks.
