### ISSUE TITLE
The NHotKey.HotKeyAlreadyRegisteredException exception seems to be non-implemented

### ISSUE THREAD

**Issue by wconnors77** [thomaslevesque/NHotkey#32]
Hi, I had a particular need to check programmatically at runtime whether or not a particular keyboard shortcut already exists, in a utility I am developing that allows users to create keyboard shortcuts (obviously I want to check so that if the user says, for example, create a keyboard shortcut using Ctrl-J, but there is already a defined/active keyboard shortcut that uses Ctrl-J, I tell them "sorry, there is already a keyboard shortcut using Ctrl-J, specify different keys for your shortcut".

So I came across this package and I love how easy it is to define keyboard shortcuts, very slick and concise. However, I saw that there were two things in the package:

1) In the second overload of the AddOrReplace method, there is a 3rd parameter, bool noRepeat.
2) There is an exception, NHotKey.HotKeyAlreadyRegisteredException, which is defined.

So I was expecting to be able to utilize these constructs to do what I needed (check for pre-existence of a keyboard shortcut). But in a test program (visual studio 2017 solution attached in a zip file), it seemed as if the noRepeat parameter being true or false made no difference, and I didn't see how to make use of the  HotKeyAlreadyRegisteredException exception (if those 2 things are even related to each other).

Are these features not fully implemented, or if so, can you clarify how to make use of them? ... and/or address the general question of whether it is possible to check for the existence of a particular keyboard shortcut before creating it.

TIA

[WindowsFormsApp1V472.zip](https://github.com/thomaslevesque/NHotkey/files/5997430/WindowsFormsApp1V472.zip)

**Comment by thomaslevesque** [comment]
Hi @wconnors77,

Thanks for your interest.

There's no relation between `noRepeat` and throwing `HotKeyAlreadyRegisteredException`.
- `noRepeat`, when set to true, means that the hotkey won't be triggered multiple times if the keyboard keys remain pressed. It corresponds to the MOD_NOREPEAT flag in the [RegisterHotKey function](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey).
- `HotKeyAlreadyRegisteredException` is thrown, as the name implies, if the same hotkey is already registered. NHotkey doesn't know anything about which hotkeys are currently registered in Windows; they could have been registered by any application, not necessarily using NHotkey (since it's just a wrapper around the RegisterHotKey function). NHotkey just throws the exception when it detects that RegisterHotKey returns a specific error code.

As far as I can tell, the only way to check if a hotkey is already registered, is trying to register it.

**Comment by wconnors77** [comment]
Hi Thomas, thanks for the reply. Gotcha on the noRepeat.

Still a bit fuzzy on the HotKeyAlreadyRegisteredException though. In my test solution, to try to test the usage of the exception, I put a catch for that exception around the AddOrReplace call and have a button on my test form, but when I click on the button repeatedly, the exception doesn't occur / get caught:

private void btnAddCtrlJKeyboardShortcut_Click(object sender, EventArgs e)
{
    try
    {
        HotKeyManager.Current.AddOrReplace("ActionJ", Keys.Control | Keys.J, true, OnActionJ);
    }
    catch (HotKeyAlreadyRegisteredException)
    { 
        textBox1.Text += Environment.NewLine + "NHotKey.HotKeyAlreadyRegisteredException";
    }
}

Am I doing something wrong here, and/or can you show a simple code example of HotKeyAlreadyRegisteredException usage?

Thanks

**Comment by thomaslevesque** [comment]
This is because `AddOrReplace` unregisters the existing hotkey with that name before registering the new one.
You would get the exception if you were registering the same hotkey with a different name

**Comment by wconnors77** [comment]
Aha! Eureka, that makes perfect sense :)

Thanks Thomas and kudos again on the NHotKey pkg.

**Comment by wconnors77** [comment]
(Should I click on the Close button or feel free to do)

**Comment by wconnors77** [comment]
No issue, needed only a clarification on usage.

**Comment by thomaslevesque** [comment]
You're welcome!
