### ISSUE TITLE
Please, add option to add gesture without HotkeyAlreadyRegisteredException with AddOrReplace method.

### ISSUE THREAD

**Issue by Samael7777** [thomaslevesque/NHotkey#46]
`AddOrReplace`  may throw an `HotkeyAlreadyRegisteredException`, which is not intercepted with `try...catch` block, and this exception may appear in other part of app.
To process the already registered hotkey, please add one of the following options:
add param `isThrowException` to `AddOrReplace` or add method `bool TryAddOrReplace`, that no throw this exception.

**Comment by thomaslevesque** [comment]
Hi @Samael7777,

> which is not intercepted with `try...catch` block

What do you mean by that? This exception is catchable like any other. As far as I can tell, there's nothing that would prevent it from being caught.

Could you please show your code?

**Comment by thomaslevesque** [comment]
Oh. You mean that currently the library doesn't catch it? When I first read it I thought you meant you were unable to catch it.

Well, it would be strange for the library to catch it, since it throws it itself. Throwing this exception is intentional, not accidental. I just created an explicit exception for this very common case (otherwise you would just get a generic HRESULT exception, which is often not very helpful).

Adding a `TryAddOrReplace` that returns a bool is of course an option; however, if it fails, how would you know _what_ caused it to fail? The key being already registered is not the only possible cause. You can read the docs for [`RegisterHotKey`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) for more details.

**Comment by Samael7777** [comment]
A part of code in composition root:
```
var availableCombinations = new List<KeyGesture>
{
    new (Key.None, ModifierKeys.Alt | ModifierKeys.Shift, "Alt+Shift"),
    new (Key.None, ModifierKeys.Control | ModifierKeys.Shift, "Ctrl+Shift")
};

_hotKeyModel = new HotKeyModel(availableCombinations, _settings.LayoutToggleHotKeyIndex);
_hotKeyModel.HotKeyPressed += (_, _) => _cycledLayoutsModel.SwitchToNextLayout();
_hotKeyModel.HotKeyAlreadyUsed += (_, _) => 
    MessageBox.Show($@"Selected combination already used in OS.", 
        "Error", MessageBoxButton.OK, MessageBoxImage.Error);

_systemSettingsChangesWatcher = new SystemSettingsWatcher();
_systemSettingsChangesWatcher.SystemLayoutsChanged += (_, _) =>
    _cycledLayoutsModel.CleanFromOrphanedLayouts();
```

Constructor and a part of a `HotKeyModel` class
```
public event EventHandler? HotKeyAlreadyUsed;

 public HotKeyModel(IEnumerable<KeyGesture> availableCombinations, int currentIndex)
 {
     _availableCombinations = new List<KeyGesture>
     {
         new (Key.None, ModifierKeys.None, "None") //No combination
     };

     _availableCombinations.AddRange(availableCombinations);

     if (currentIndex < 0 || currentIndex >= _availableCombinations.Count)
         throw new ArgumentOutOfRangeException(nameof(currentIndex));

     HotKeyIndex = currentIndex;
     HotkeyManager.HotkeyAlreadyRegistered += OnAlreadyRegistered;
 }

private void OnAlreadyRegistered(object? sender, HotkeyAlreadyRegisteredEventArgs e)
{
    _currentKeyIndex = 0;
    OnPropertyChanged(nameof(HotKeyIndex));

    HotKeyAlreadyUsed?.Invoke(this, EventArgs.Empty);
}
```

Method `SetNewHotKey` where sets new hotkey:
```
private void SetNewHotKey(int index)
{
    if (index < 0 || index >= _availableCombinations.Count)
        throw new ArgumentOutOfRangeException(nameof(index));

    if (_currentKeyIndex == index) return;

    _currentKeyIndex = index;
    var gesture = _availableCombinations[index];
    HotkeyManager.Current.Remove(GestureName);
    try
    {
        HotkeyManager.Current.AddOrReplace(GestureName, gesture, true, OnHotKeyPressed);
    }
    catch (HotkeyAlreadyRegisteredException)
    {
        HotKeyIndex = 0;
    }
}
```

I'm sorry, I said it not quite correctly, my mistake :) catch block works, but `HotkeyAlreadyRegistered ` event not rises, and I have such strange thing:


![Снимок экрана 2024-10-27 093319](https://github.com/user-attachments/assets/37f77a49-6726-405e-965c-4700de4a43db)

Exception: `The assigned key is already registered.`
This part of code is not connected in any way with hotkeys.

**Comment by Samael7777** [comment]
Found a problem in my code. `Marshal.GetHRForLastWin32Error()` get an error code from hotkey registration and `Marshal.GetExceptionForHR()` get an exception...

**Comment by Samael7777** [comment]
But event still not works....

**Comment by thomaslevesque** [comment]
Ah, I see what you mean.
The `HotkeyManager.HotkeyAlreadyRegistered` event is only raised when adding hotkeys via XAML, by adding a keybinding with `RegisterGlobalHotkey` set to true (because there would be no way to catch the error otherwise). It's not raised when calling `AddOrReplace`. I realize it can be confusing, and it should probably be made more explicit in the documentation.
So basically, if you're not setting the hotkeys via XAML, you shouldn't rely on the `HotkeyAlreadyRegistered` event, only on the exception.
Does this help?

**Comment by Samael7777** [comment]
Yes, already do that 👍 Thanks for help!
