### ISSUE TITLE
Binding The Escape Key Non-Exclusively

### ISSUE THREAD

**Issue by AtmoEntity** [thomaslevesque/NHotkey#6]
I am binding an event to the Escape key, but when I do that other applications (such as Window's Snap Assist) no longer gets the event. Is there any way to bind the event and still allow other things to receive the event?

**Comment by thomaslevesque** [comment]
Hi,

No, it's not possible with NHotkey, because it's based on the `RegisterHotkey` Windows API, and a hotkey registered that way is suppressed in other applications. If you want to intercept a key globally without preventing it from being received by other apps, you will need a global system hook. Have a look at this article: http://www.codeproject.com/Articles/7294/Processing-Global-Mouse-and-Keyboard-Hooks-in-C

**Comment by AtmoEntity** [comment]
Ah okay.

Great library! Thanks.
