### ISSUE TITLE
How to bind global key without key modifier?

### ISSUE THREAD

**Issue by allanruin** [thomaslevesque/NHotkey#9]
I writing a software that I would like to invoke my software when user press backtick key, ` HotkeyManager.Current.AddOrReplace` require the KeyModifier , is it possible to bind single key short-cut with NHotkey?

**Comment by thomaslevesque** [comment]
Hi @allanruin,

No, it's not supported. Apparently the [RegisterHotKey](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309) function (on which NHotkey relies) supports registering a hotkey with no modifiers (just use `None` as the modifier), but it won't be global (it will only work in the current window)

**Comment by JobaDiniz** [comment]
You're saying I can't use NHotkey for global `F8` shortcut?

**Comment by thomaslevesque** [comment]
@JobaDiniz, no, you can't, because the underlying Windows API doesn't support it.

**Comment by thomaslevesque** [comment]
Actually, I just tried again to register just F8 or A as a hotkey without a modifier, and it seems to work... Not sure if something changed in Windows since this issue was opened, but I'm pretty sure it didn't work before.

Anyway, registering a hotkey without a modifier is probably not a good idea. For instance, if you register A, you can no longer type the letter A in other apps...
